-- Creacion de tablas segun el modelo E/R (PostgreSQL)

-- Limpieza opcional para poder re-ejecutar el script sin errores
DROP TABLE IF EXISTS LISTA_AMIGOS;
DROP TABLE IF EXISTS PARTICIPACION;
DROP TABLE IF EXISTS PARTIDA;
DROP TABLE IF EXISTS JUGADOR;

-- Tabla de jugadores
CREATE TABLE JUGADOR (
    ID                   INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE               VARCHAR(100) NOT NULL,
    CONTRASENA           VARCHAR(100) NOT NULL,
    URL_IMG_PERFIL       VARCHAR(255),
    SKIN_FICHAS          VARCHAR(120),
    SKIN_TABLERO         VARCHAR(120),
    MONEDAS              INT NOT NULL DEFAULT 0,
    PARTIDAS_GANADAS     INT NOT NULL DEFAULT 0,
    PARTIDAS_PERDIDAS    INT NOT NULL DEFAULT 0,
    PARTIDAS_EMPATADAS   INT NOT NULL DEFAULT 0,
    PARTIDAS_PENDIENTES  INT NOT NULL DEFAULT 0,
    PARTIDAS_FINALIZADAS INT NOT NULL DEFAULT 0
);

-- Tabla de partidas
CREATE TABLE PARTIDA (
    ID_PARTIDA INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TURNO      INT NOT NULL,
    FECHA      DATE NOT NULL,
    MERCADO    VARCHAR(5000),
    BOLSA      VARCHAR(5000),
    CONJUNTO_MESA VARCHAR(10000),
    EVENTO_ACTUAL VARCHAR(120),
    MODO_ARCADE BOOLEAN NOT NULL DEFAULT FALSE,
    TURNO_INICIO TIMESTAMP,
    ESTADO     VARCHAR(20),
    GANADOR_ID INT,
    PUNTUACION_FINAL VARCHAR(2000),
    PRIVADA    BOOLEAN NOT NULL DEFAULT FALSE,
    CORRIENDO  BOOLEAN NOT NULL DEFAULT FALSE
);

-- Tabla intermedia de participacion (relacion muchos-a-muchos con atributos)
CREATE TABLE PARTICIPACION (
    ID_JUGADOR           INT NOT NULL,
    ID_PARTIDA           INT NOT NULL,
    FICHAS_ACTUALES      INT NOT NULL,
    HABILIDADES_ACTUALES VARCHAR(1000),
    MANO_ACTUAL          VARCHAR(5000),
    ORDEN_TURNO          INT,
    TURNOS_INACTIVO      INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ID_JUGADOR, ID_PARTIDA),
    FOREIGN KEY (ID_JUGADOR) REFERENCES JUGADOR(ID),
    FOREIGN KEY (ID_PARTIDA) REFERENCES PARTIDA(ID_PARTIDA)
);

-- Tabla de lista de amigos (relacion entre jugadores)
CREATE TABLE LISTA_AMIGOS (
    ID_JUGADOR INT NOT NULL,
    ID_AMIGO   INT NOT NULL,
    FECHA      DATE NOT NULL,
    ESTADO     VARCHAR(50) NOT NULL,
    PRIMARY KEY (ID_JUGADOR, ID_AMIGO),
    FOREIGN KEY (ID_JUGADOR) REFERENCES JUGADOR(ID),
    FOREIGN KEY (ID_AMIGO) REFERENCES JUGADOR(ID)
);
